# Generated by Django 4.0 on 2023-04-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_experience_rename_about_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='picture',
            new_name='image',
        ),
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
