# Generated by Django 4.0 on 2023-04-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_picture_blog_image_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='demolink',
            field=models.URLField(blank=True, null=True),
        ),
    ]
